### ISSUE TITLE
Kibana 4 support

### ISSUE THREAD

**Issue by axot** [magenx/WAZUH-OSSEC#3]
How to use this dashboard in kibana4,
Thank you.

**Comment by magenx** [comment]
it will not work for latest ELK stack, they have changed a lot.

**Comment by pjmorr** [comment]
You might want to check out [ossec-wazuh](https://github.com/wazuh/ossec-wazuh)  
I loved this dashboard in kibana 3. Might just see if I can reproduce since I have all the data.

**Comment by axot** [comment]
@pjmorr Thanks for your suggestion. ossec-wazuh seems so powerful ;D
